# Generated by Django 5.0.1 on 2024-03-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_url", models.URLField(verbose_name="Источник")),
                (
                    "short_text",
                    models.TextField(verbose_name="Сокращённый текст"),
                ),
                ("full_text", models.TextField(verbose_name="Полный текст")),
            ],
        ),
    ]
