# Generated by Django 5.0.4 on 2024-05-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_digest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="digest",
            name="title",
            field=models.CharField(max_length=500, verbose_name="Заголовок"),
        ),
    ]
