# Generated by Django 5.0.4 on 2024-05-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_digest_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="source_url",
            field=models.URLField(max_length=255, verbose_name="Источник"),
        ),
        migrations.AlterField(
            model_name="digest",
            name="title",
            field=models.CharField(max_length=300, verbose_name="Заголовок"),
        ),
    ]
